const fs = require('fs');
const path = require('path');

const envPath = path.join(__dirname, '.env');
const envJsDir = path.join(__dirname, 'js');
const envJsPath = path.join(envJsDir, 'env.js');

let envVars = {};

if (fs.existsSync(envPath)) {
  const content = fs.readFileSync(envPath, 'utf8');
  content.split(/\r?\n/).forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const parts = trimmed.split('=');
    if (parts.length >= 2) {
      const key = parts[0].trim();
      // Exclude private administrative secrets from public client context
      if (['SUPABASE_SERVICE_ROLE_KEY', 'RESEND_API', 'CLOUDINARY_API_SECRET'].includes(key)) return;
      const val = parts.slice(1).join('=').trim();
      // Remove surrounding quotes if any
      envVars[key] = val.replace(/^['"]|['"]$/g, '');
    }
  });
  console.log('Successfully loaded .env variables.');
} else {
  console.warn('Warning: .env file not found. Client configuration fallback keys will be used.');
}

const jsContent = `/* Generated by generate-env.js — DO NOT EDIT DIRECTLY */
window.ENV = ${JSON.stringify(envVars, null, 2)};
`;

if (!fs.existsSync(envJsDir)) {
  fs.mkdirSync(envJsDir, { recursive: true });
}

fs.writeFileSync(envJsPath, jsContent, 'utf8');
console.log('Generated js/env.js file.');
